# [build]
# rustflags = ["--cfg=web_sys_unstable_apis"]
# --cfg=web_sys_unstable_apis
# --cfg=web_sys_unstable_apis wasm-pack build --target web

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-ObjC"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-ObjC"]

[target.aarch64-apple-ios]
rustflags = ["-C", "link-args=-ObjC"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-args=-ObjC"]